top_crypto_dict = {
    "BTC": "Bitcoin",
    "ETH": "Ethereum",
    "XRP": "XRP",
    "USDT": "Tether",
    "BNB": "BNB",
    "SOL": "Solana",
    "DOGE": "Dogecoin",
    "USDC": "USD Coin",
    "ADA": "Cardano",
    "TRX": "TRON",
    "AVAX": "Avalanche",
    "SUI": "Sui",
    "TON": "Toncoin",
    "XLM": "Stellar",
    "SHIB": "Shiba Inu",
    "LINK": "Chainlink",
    "HBAR": "Hedera",
    "DOT": "Polkadot",
    "LEO": "UNUS SED LEO",
    "BCH": "Bitcoin Cash",
    "UNI": "Uniswap",
    "LTC": "Litecoin",
    "NEAR": "NEAR Protocol",
    "DAI": "Dai",
    "APT": "Aptos",
    "ICP": "Internet Computer",
    "AAVE": "Aave",
    "XMR": "Monero",
    "MNT": "Mantle",
    "ETC": "Ethereum Classic",
    "POL": "POL (ex-MATIC)",
    "OM": "MANTRA",
    "RNDR": "Render",
    "CRO": "Cronos",
    "VET": "VeChain",
    "FIL": "Filecoin",
    "FET": "Fetch.ai",
    "KAS": "Kaspa",
    "ARB": "Arbitrum",
    "ALGO": "Algorand",
    "OKB": "OKB",
    "ATOM": "Cosmos",
    "OP": "Optimism",
    "TIA": "Celestia",
    "STX": "Stacks",
    "THETA": "Theta Network",
    "IMX": "Immutable",
    "INJ": "Injective",
    "GRT": "The Graph",
    "QNT": "Quant",
    "NoCoin": "NoCoin",
}
